[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
  publish = "build"
  autoLaunch = true

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom error pages
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/403.html"
  status = 403

[[redirects]]
  from = "/*"
  to = "/401.html"
  status = 401

[[redirects]]
  from = "/*"
  to = "/500.html"
  status = 500

[build.environment]
  NODE_VERSION = "16"